---

- hosts: all
  become: true

  vars: 
    source_folder: ./files
    destin_folder: /var/www/html

  tasks:
    - name: Check and Print Linux Version
      debug: var=ansible_os_family

    - block: # ======Block for Debian =======
      - name: Update Debian Servers
        tags: always
        apt:
          upgrade: dist

      - name: Install Apache Server on Debian
        tags: apache, apache2, debian
        apt:
          name: apache2
          state: latest

      when: ansible_distribution_file_variety == "Debian"

    - block: #==========Block for RedHat========
      - name: Update RedHat Servers
        tags: always
        yum:
          update_only: yes
          update_cache: yes

      - name: Install Apache Server on CentOS
        tags: apache, centos, httpd
        yum:
          name: httpd
          state: latest

      when: ansible_distribution_file_variety == "RedHat"

    - name: Generate Index.html
      template: src={{ source_folder }}/default_site.j2 dest={{ destin_folder }}/index.html mode=0555
      notify:
        - Restart Apache Debian
        - Restart Apache RedHat 


  handlers:
  - name: Restart Apache Debian
    service: name=apache2 state=restarted
    when: ansible_distribution_file_variety == "Debian"

  - name: Restart Apache RedHat
    service: name=httpd state=restarted
    when: ansible_distribution_file_variety == "RedHat"